name: Deploy CI

on:
  workflow_run:
    workflows: ["Publish"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate with GitHub Container Registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
        
      - name: Run Docker Compose Pull
        run: docker-compose -f /home/iacd/joao-guedes/ABI-Interoperability/docker-compose.yaml pull

      - name: Run Docker Compose Up
        run: docker-compose -f /home/iacd/joao-guedes/ABI-Interoperability/docker-compose.yaml up -d
